apiVersion: v1
kind: Service
metadata:
  name: caresync-q-careplan
  labels:
    app.kubernetes.io/name: caresync-q-careplan
    app.kubernetes.io/part-of: caresync
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: caresync-q-careplan
  ports:
    - name: http
      port: 8094
      targetPort: http
