apiVersion: v1
kind: Service
metadata:
  name: caresync-q-alert
  labels:
    app.kubernetes.io/name: caresync-q-alert
    app.kubernetes.io/part-of: caresync
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: caresync-q-alert
  ports:
    - name: http
      port: 8093
      targetPort: http
