apiVersion: v1
kind: Service
metadata:
  name: caresync-q-messaging
  labels:
    app.kubernetes.io/name: caresync-q-messaging
    app.kubernetes.io/part-of: caresync
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: caresync-q-messaging
  ports:
    - name: http
      port: 8098
      targetPort: http
