apiVersion: v1
kind: Service
metadata:
  name: caresync-q-prescription
  labels:
    app.kubernetes.io/name: caresync-q-prescription
    app.kubernetes.io/part-of: caresync
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: caresync-q-prescription
  ports:
    - name: http
      port: 8095
      targetPort: http
