apiVersion: v1
kind: Service
metadata:
  name: caresync-q-analytics
  labels:
    app.kubernetes.io/name: caresync-q-analytics
    app.kubernetes.io/part-of: caresync
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: caresync-q-analytics
  ports:
    - name: http
      port: 8099
      targetPort: http
