apiVersion: v1
kind: Service
metadata:
  name: caresync-q-gateway
  labels:
    app.kubernetes.io/name: caresync-q-gateway
    app.kubernetes.io/part-of: caresync
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: caresync-q-gateway
  ports:
    - name: http
      port: 8090
      targetPort: http
