apiVersion: v1
kind: Service
metadata:
  name: caresync-q-dossier
  labels:
    app.kubernetes.io/name: caresync-q-dossier
    app.kubernetes.io/part-of: caresync
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: caresync-q-dossier
  ports:
    - name: http
      port: 8096
      targetPort: http
