apiVersion: v1
kind: Service
metadata:
  name: caresync-q-patient
  labels:
    app.kubernetes.io/name: caresync-q-patient
    app.kubernetes.io/part-of: caresync
    app.kubernetes.io/component: backend
spec:
  selector:
    app.kubernetes.io/name: caresync-q-patient
  ports:
    - name: http
      port: 8097
      targetPort: http
